/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface AppHome {}
  interface AppProfile {
    'name': string;
  }
  interface AppRoot {}
  interface ProfileCreator {}
  interface SpeechDetail {
    'session': any;
  }
  interface SpeechModal {}
}

declare global {


  interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {}
  var HTMLAppHomeElement: {
    prototype: HTMLAppHomeElement;
    new (): HTMLAppHomeElement;
  };

  interface HTMLAppProfileElement extends Components.AppProfile, HTMLStencilElement {}
  var HTMLAppProfileElement: {
    prototype: HTMLAppProfileElement;
    new (): HTMLAppProfileElement;
  };

  interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {}
  var HTMLAppRootElement: {
    prototype: HTMLAppRootElement;
    new (): HTMLAppRootElement;
  };

  interface HTMLProfileCreatorElement extends Components.ProfileCreator, HTMLStencilElement {}
  var HTMLProfileCreatorElement: {
    prototype: HTMLProfileCreatorElement;
    new (): HTMLProfileCreatorElement;
  };

  interface HTMLSpeechDetailElement extends Components.SpeechDetail, HTMLStencilElement {}
  var HTMLSpeechDetailElement: {
    prototype: HTMLSpeechDetailElement;
    new (): HTMLSpeechDetailElement;
  };

  interface HTMLSpeechModalElement extends Components.SpeechModal, HTMLStencilElement {}
  var HTMLSpeechModalElement: {
    prototype: HTMLSpeechModalElement;
    new (): HTMLSpeechModalElement;
  };
  interface HTMLElementTagNameMap {
    'app-home': HTMLAppHomeElement;
    'app-profile': HTMLAppProfileElement;
    'app-root': HTMLAppRootElement;
    'profile-creator': HTMLProfileCreatorElement;
    'speech-detail': HTMLSpeechDetailElement;
    'speech-modal': HTMLSpeechModalElement;
  }
}

declare namespace LocalJSX {
  interface AppHome {}
  interface AppProfile {
    'name'?: string;
  }
  interface AppRoot {}
  interface ProfileCreator {}
  interface SpeechDetail {
    'session'?: any;
  }
  interface SpeechModal {}

  interface IntrinsicElements {
    'app-home': AppHome;
    'app-profile': AppProfile;
    'app-root': AppRoot;
    'profile-creator': ProfileCreator;
    'speech-detail': SpeechDetail;
    'speech-modal': SpeechModal;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'app-home': LocalJSX.AppHome & JSXBase.HTMLAttributes<HTMLAppHomeElement>;
      'app-profile': LocalJSX.AppProfile & JSXBase.HTMLAttributes<HTMLAppProfileElement>;
      'app-root': LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
      'profile-creator': LocalJSX.ProfileCreator & JSXBase.HTMLAttributes<HTMLProfileCreatorElement>;
      'speech-detail': LocalJSX.SpeechDetail & JSXBase.HTMLAttributes<HTMLSpeechDetailElement>;
      'speech-modal': LocalJSX.SpeechModal & JSXBase.HTMLAttributes<HTMLSpeechModalElement>;
    }
  }
}


